### ISSUE TITLE
Remove message bubble background and rounded corners

### ISSUE THREAD

**Issue by iacore** [krille-chan/fluffychat#1035]
### Feature Description

The newest design of Fluffychat UI brings two-color chat bubbles with uneven corner radius. The corner radius changes when new messages are received. The app background is also brighter than the system UI.

I like the old background color. I want all message text to be the same color, and without background.

### Rationale

I want to be able to look at the Fluffychat UI.

**Comment by krille-chan** [comment]
Using the primary color with white text (or black text for dark style) is common sense in a lot of modern messengers out there. If this makes you unable to look at the GUI, I'm very sorry, there is nothing I can do for you.

> The corner radius changes when new messages are received.

Connecting message bubbles from the same sender in an equal time frame is a **feature** which has been requested a lot. I'm not gonna removing it.

It sounds like your issue is just about your personal taste but not a bug or a real improvement. There won't be any further discussion about this!

**Comment by iacore** [comment]
the text bubbles i send has dark text on bright background. the text bubbles i receive has bright text on dark background.
