### ISSUE TITLE
Animated emojis do not work

### ISSUE THREAD

**Issue by bq3p9** [krille-chan/fluffychat#1071]
### Bug Description

FluffyChat does not support animated emojis because it currently loads them with the following URL format:

```https://matrix-client.matrix.org/_matrix/media/v3/thumbnail/matrix.org/<ID>?width=32&height=32&method=scale&animated=true```

However, the actual URL format should be:

```https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/<ID>```

This loads the full resolution emoji and keeps the MIME type for animated emotes (APNG, WEBP, etc)

### Steps to Reproduce

1. Create an animated emoji using nheko or cinny
2. Send a message with the emoji
3. Look on FluffyChat and the emoji will not be animated

### Expected Behavior

The emoji should be animated.

### App Version

1.19.2

### Additional Platform Information

Linux, Android, iOS, Windows, and web

### Additional Context

CC @krille-chan

**Comment by RiedleroD** [comment]
testing animated emoji rn, and it seems apng it was still working in 1.19.0-3 (from the AUR package)

gif are static tho. not sure if that's intended behaviour. also I can't even upload webp at all, since they're excluded from the filepicker… will have to try uploading them via other means…

**Comment by everypizza1** [comment]
Some people are saying that when I send an animated emoji from FluffyChat, it appears still for non FluffyChat users. The same happens when they send animated stickers.

**Comment by RiedleroD** [comment]
@everypizza1 in your case it's probably fluffy supporting apng, but not gif, and whatever the other clients are support gif but not apng.

**Comment by Schlaftablette** [comment]
Just tried the Fluffychat **web** chat https://fluffychat.im/, uploaded the animated GIF from a local drive but Fluffychat **web** did not animate it. Then I converted the GIF to APNG with `ffmpeg -i wink.gif wink.apng`, uploaded it and it did not animate. Also it got blurred (while the GIF is displayed correctly).

I attached the GIF to this comment.

![wink](https://github.com/user-attachments/assets/5fcda84b-b799-4234-b2a0-10f84a0c1e42)

**Comment by marekvospel** [comment]
Looking into this, overall most images are loaded as thumbnails (including emojis, stickers, reactions etc.), which is a problem for animated / transparent emojis.

Example of a transparent image:
![image](https://github.com/user-attachments/assets/b6eabd18-b7f3-4bc7-afb4-adce0b9b3c81)  
![image](https://github.com/user-attachments/assets/b3cc669d-81fc-40bc-bf9d-72fd5f22aa4c)  

MxcImage - isThumbnail = true
https://github.com/krille-chan/fluffychat/blob/325431c8f668d376f1ff5976c79116dfc115aef4/lib/widgets/mxc_image.dart#L35
HtmlMessage (isThumbnail is not overriden)
https://github.com/krille-chan/fluffychat/blob/325431c8f668d376f1ff5976c79116dfc115aef4/lib/pages/chat/events/html_message.dart#L279
Settings emotes (isThumbnail is not overriden)
https://github.com/krille-chan/fluffychat/blob/325431c8f668d376f1ff5976c79116dfc115aef4/lib/pages/settings_emotes/settings_emotes_view.dart#L245
https://github.com/krille-chan/fluffychat/blob/325431c8f668d376f1ff5976c79116dfc115aef4/lib/pages/chat/events/message_reactions.dart#L120
Message reaction (isThumbnail is not overriden)
https://github.com/krille-chan/fluffychat/blob/325431c8f668d376f1ff5976c79116dfc115aef4/lib/pages/chat/input_bar.dart#L271
Wallpaper (isThumnail is not overriden)
https://github.com/krille-chan/fluffychat/blob/325431c8f668d376f1ff5976c79116dfc115aef4/lib/pages/settings_style/settings_style_view.dart#L179
https://github.com/krille-chan/fluffychat/blob/325431c8f668d376f1ff5976c79116dfc115aef4/lib/pages/chat/chat_view.dart#L273

The question is what to do about this. In some places like message reactions or settings, isThumbnail can be simply set to false, however for example html message can't just render everything as isThumbnail = false. I think this could be solved by rendering it as thumbnail in case it is bigger than 256x256 (65536 pixels) and setting the value to false otherwise.

I'll try to make a PR later today, that does just that.
