### ISSUE TITLE
Push notifications are delivered to the device despite being active on another

### ISSUE THREAD

**Issue by K4LCIFER** [krille-chan/fluffychat#532]
### Bug Description

Say you are currently active on a desktop where you have element-desktop installed, and you receive a message. Instaed of just receiving the message on the desktop, you will receive the message on every device including a mobile device that has fluffychat.

### Steps to Reproduce

1. Be active on another device
2. observe that notifications get sent to fluffychat on mobile

### Expected Behavior

I expect notifications to only be pushed to devices that are active.

### App Version

1.13.0

### Additional Platform Information

Pixel 6, android 14 beta

**Comment by jivanpal** [comment]
> I expect notifications to only be pushed to devices that are active.

What do you consider to be an "active device"? As far as I can see, this is normal, expected behaviour for any messaging app where you may be logged in to your account in multiple places at once; all sessions receive notifications, and should receive automatic notification dismissals if/when the message is read in any one session.
