### ISSUE TITLE
Android system notifications settings for fluffychat should not  have options to toggle settings per space. This should only be toggleable within the app

### ISSUE THREAD

**Issue by K4LCIFER** [krille-chan/fluffychat#533]
### Feature Description

Currently in the android system settings for fluffychat notifications, you have the ability to toggle notifications for spaces. This seems like a werid place. This should only be in the app.

### Rationale

To keep settings within their scope, settings pertaining the app on the whole should be in the android app settings, and settings within the app should be within the app.

**Comment by K4LCIFER** [comment]
> the official Google Messages app for Android gives each conversation its own notification settings

Hm, well, be that as it may, it honestly feels like bad UX.

**Comment by dshatz** [comment]
I disagree. Having these settings in a standard place is the way it should be. Easier to find and toggle right from notification drawer than digging though settings in every app.

**Comment by Gnorv** [comment]
I somewhat agree with @CorvetteCole that having these settings in a unified place is good, however @K4LCIFER has a point in that now the UX is not the best.

I would like to change the notification sound of FluffyChat so that I can distinguish it from SMS or Signal messages.

As it is now I have to go through the system settings and change the sound for each space/chat individually. If it were possible to set a default tone for direct chats, another for groups in addition to the functionality to set individual tones that would be great.
