### ISSUE TITLE
Voicemassage

### ISSUE THREAD

**Issue by Mutz88** [krille-chan/fluffychat#592]
### Bug Description

Whenever I receive a voice message and want to listen to it, I get an error message. The voice message is also displayed with a length of 0.00.

### Steps to Reproduce

Go to a chat in which you have received a voice message and try to listen to it.

### Expected Behavior

Functioning voice messages. 

### App Version

1.14.1

### Additional Platform Information

iPhone 11pro

**Comment by MtFBella109** [comment]
Have the same Bug I'm using FluffyChat on iPhone 12 Mini with iOS 17.1. For me it shows the length, but if I want to hear it, I get there is a Error (Don't know the exactly Error in English because my App is on German) It happens for all my voice Messages that I receive, but I receive them only via the WhatsApp Bridge from People from WhatsApp

**Comment by MtFBella109** [comment]
And If I make voice messages, they don‘t get bridged via the WhatsApp bridge
