### ISSUE TITLE
Message (copied from another room) was sent without input/interaction from me

### ISSUE THREAD

**Issue by enterprisey** [krille-chan/fluffychat#760]
### Bug Description

I had a room open, then I went back to the room switcher and opened another room. When I did that, there seemed to be a brief lag, and then the app took the text of the most recent message from the room I left, and __sent it as a new message from me without my involvement__ to the new room.

(I don't actually remember for sure that I was in the room the message was from before hand, but I might've been. I was at the room switcher for sure and the message was definitely triggered by opening the room.)

### Steps to Reproduce

Unfortunately I don't have anything. I have not seen the bug since.

### Expected Behavior

I expected this to not happen.

### App Version

1.16.0

### Additional Platform Information

android 9

**Comment by krille-chan** [comment]
I assume for some reason the message landed in the `shareContent` variable in the appstate. Without more information I assume that this happened because of somehow misclicked a button.

I will change it in a way that sharing text does not send text directly to a chat but just puts it into the input field and the user has to press the send button before it gets sent.
